name: ci esdk-obs-java

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build with Maven
      run: mvn clean install -f pom-java.xml
    - name: mk dir 
      run: mkdir esdk-obs-java-cn-on-github
    - name: cp files
      run: cp /home/runner/work/huaweicloud-sdk-java-obs/huaweicloud-sdk-java-obs/target/esdk-obs-java-* ./esdk-obs-java-cn-on-github
    - name: Build Zip File
      uses: thedoctor0/zip-release@master
      with:
        filename: 'test.zip'
        path:  /home/runner/work/huaweicloud-sdk-java-obs/huaweicloud-sdk-java-obs/target/
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
      #uses: montudor/action-zip@v0.1.0
      #with:
      #    args: zip -qq -r ./esdk-obs-java-cn-on-github/huaweicloud-obs-sdk-java_3.20.1.zip /home/runner/work/huaweicloud-sdk-java-obs/huaweicloud-sdk-java-obs/target/
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@master
      with:
        # Artifact name
        name: esdk-obs-java-cn-on-github
        # Destination path
        path: ./esdk-obs-java-cn-on-github/
    #- name: sbt to Maven Central
    #  uses: cosmincatalin/sbt-to-maven-central@v1.0.6
