name: ci esdk-obs-java

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build Java SDK - CN
      run: mvn clean install -f pom-java.xml
    - name: Mkdir For Java SDK 
      run: mkdir esdk-obs-java-cn-on-github
    - name: cp file java sdk into output directory
      run: cp /home/runner/work/huaweicloud-sdk-java-obs/huaweicloud-sdk-java-obs/target/esdk-obs-java-* ./esdk-obs-java-cn-on-github
    - name: Build Java Optimization SDK - CN
      run: mvn clean install -f pom-java-optimization.xml
    - name: cp file java optimization sdk into output directory
      run: cp /home/runner/work/huaweicloud-sdk-java-obs/huaweicloud-sdk-java-obs/target/esdk-obs-java-optimization-*.jar ./esdk-obs-java-cn-on-github
      
    - name: Upload Java SDK - CN
      if: success()
      uses: actions/upload-artifact@master
      with:
        # Artifact name
        name: esdk-obs-java-cn-on-github
        # Destination path
        path: ./esdk-obs-java-cn-on-github/
      
    - name: Build Android SDK - CN
      run: mvn clean install -f pom-android.xml
    - name: Mkdir For Android SDK
      run: mkdir esdk-obs-android-cn-on-github
    - name: cp file android sdk into output directory
      run: cp /home/runner/work/huaweicloud-sdk-java-obs/huaweicloud-sdk-java-obs/target/esdk-obs-android-* ./esdk-obs-android-cn-on-github
    - name: Upload Android SDK - CN
      if: success()
      uses: actions/upload-artifact@master
      with:
        # Artifact name
        name: esdk-obs-android-cn-on-github
        # Destination path
        path: ./esdk-obs-android-cn-on-github/
